services:
  nextjs:
    container_name: roman_blog_fe
    build: 
      context: .
      args:
        NEXT_PUBLIC_BASE_URL: http://ec2-54-209-224-117.compute-1.amazonaws.com:3001
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://ec2-54-209-224-117.compute-1.amazonaws.com:3001
    networks:
      - shared-net

networks:
  shared-net:
    external: true