services:
  nextjs:
    container_name: roman_blog_fe
    build: 
      context: .
      args:
        NEXT_PUBLIC_BASE_URL: http://be.roman.localhost
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://be.roman.localhost
    networks:
      - shared-net

networks:
  shared-net:
    external: true